Resources/Prototypes/Maps/Pools/default.yml, Resources/Prototypes/Maps/bagel.yml, Resources/Prototypes/Maps/box.yml, Resources/Prototypes/Maps/fland.yml, Resources/Prototypes/Maps/marathon.yml, Resources/Prototypes/Maps/meta.yml, Resources/Prototypes/Maps/saltern.yml
=> Adjust Maps

Resources/Prototypes/Maps/bagel.yml, Resources/Prototypes/Maps/box.yml, Resources/Prototypes/Maps/fland.yml, Resources/Prototypes/Maps/marathon.yml, Resources/Prototypes/Maps/meta.yml, Resources/Prototypes/Maps/saltern.yml
=> Map Adjust Fix

Resources/Audio/Lobby/attributions.yml, Resources/Prototypes/SoundCollections/lobby.yml
=> Re-Add Monument Lobby Song

Content.Server/Chat/SuicideSystem.cs
Copied a Delta-V PR to prevent suicide https://github.com/DeltaV-Station/Delta-v/pull/84.
=> Prevent Suicide

Resources/Prototypes/Catalog/Fills/Lockers/service.yml
Gave clown stuff to fill their locker.
What's the point of having a locker if you have nothing to put in it!
**Changelog**
:cl:
- add: Added Clown items to Clown's Locker
=> Clown Locker Filled

Resources/Changelog/Changelog.yml, Resources/Prototypes/Reagents/narcotics.yml
=> Merge Upstream

Resources/Prototypes/Maps/Pools/default.yml, Resources/Prototypes/Maps/bagel.yml, Resources/Prototypes/Maps/meta.yml, Resources/Prototypes/Maps/origin.yml
Added a low-pop map back to the pool and re-added Origin Station.
Mapa time
**Changelog**
:cl:
- add: Added Origin Station and low-pop map Reach
=> Adjusted Maps

Resources/Locale/en-US/greystation/ghost/roles/ghost-role-component.ftl, Resources/Locale/en-US/greystation/interaction/interaction-popup-component.ftl, Resources/Prototypes/GreyStation/Entities/Mobs/NPCs/xeno.yml
Added Changes + Ghost Role Components
She deserves a name and proper roles description.
**Changelog**
:cl:
- add: Added Xeno Maid's new name, Vasquez
- add: Added Proper Ghost Role components
=> Xeno Maid Changes

Content.Server/StationEvents/Events/IonStormRule.cs, Resources/Locale/en-US/station-events/events/ion-storm.ftl
Fixed errors from https://github.com/greystation14/GreyStation14/pull/53
=> Fix Ion Storm

.github/workflows/changelog.yml, Resources/Changelog/Admin.yml, Resources/Changelog/Changelog.yml, Resources/Changelog/GreyStationChangelog.yml, Resources/Locale/en-US/changelog/changelog-window.ftl, Tools/changelog/changelog.js, Tools/changelog/package.json
**Changelog**
:cl:
- add: Added automatic changelogs
=> Added Automatic Change Logs

Content.Shared/CCVar/CCVars.cs
Added character description flavor text in the character creation menu.
**Changelog**
:cl:
- add: Added Character Flavor Text
=> Added Flavor text

Content.Shared/CCVar/CCVars.cs
Reverts greystation14/GreyStation14#57
=> Revert "Added Flavor text"

Content.Shared/Access/Components/IdCardConsoleComponent.cs, Resources/Locale/en-US/prototypes/access/accesses.ftl, Resources/Prototypes/Access/medical.yml, Resources/Prototypes/Access/misc.yml, Resources/Prototypes/Access/service.yml, Resources/Prototypes/DeltaV/Access/cargo.yml, Resources/Prototypes/DeltaV/Access/medical.yml, Resources/Prototypes/DeltaV/Access/service.yml, Resources/Prototypes/Entities/Objects/Tools/access_configurator.yml, Resources/Prototypes/Entities/Structures/Doors/Airlocks/access.yml, Resources/Prototypes/Roles/Jobs/Civilian/clown.yml, Resources/Prototypes/Roles/Jobs/Civilian/librarian.yml, Resources/Prototypes/Roles/Jobs/Civilian/mime.yml, Resources/Prototypes/Roles/Jobs/Civilian/musician.yml, Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml, Resources/Prototypes/Roles/Jobs/Medical/chief_medical_officer.yml, Resources/Prototypes/Roles/Jobs/Wildcards/boxer.yml, Resources/Prototypes/Roles/Jobs/Wildcards/psychologist.yml, Resources/Prototypes/Roles/Jobs/Wildcards/reporter.yml, Resources/Prototypes/Roles/Jobs/Wildcards/zookeeper.yml
A port of https://github.com/DeltaV-Station/Delta-v/commit/ce00812d953bac3c7e8d28b0a0d063f968c5c409 from Delta-V
Clown/Mime should have separate rooms....trust me. 
**Changelog**
:cl:
- add: Added Adds Robust Granular Access
=> Adds Robust Granular Access

Resources/Prototypes/DeltaV/Entities/Clothing/OuterClothing/vests.yml
Added flak vest prototypes
**Changelog**
:cl:
- add: Added flak jackets
=> Add Delta-V Flak Vests

Resources/Prototypes/Nyanotrasen/Entities/Objects/Power/lights.yml, Resources/Prototypes/Nyanotrasen/Entities/Structures/Lighting/base_lighting.yml
Nyano lights from Nyano
The Weeknd "all of the lights" 
**Changelog**
:cl:
- add: Added Nyano Lights
=> Added lights from Nyano

Resources/Locale/en-US/paper/book-salvage.ftl, Resources/Prototypes/Catalog/Fills/Books/lore.yml
Added a awful book from ss13 that was really funny. Source of the book https://wiki.ss13.co/Sex_and_the_Singularity
It's funny
**Changelog**
:cl:
- add: Added a Singularity book
=> Added Singularity Book

Content.Server/DeltaV/Administration/Commands/LoadCharacter.cs, Content.Server/DeltaV/Administration/Commands/SpawnCharacter.cs, Resources/Locale/en-US/administration/commands/load-character.ftl
Added the Delta-V command of being able to load yours or others character's. You can do so by doing loadcharacter (whatever the human mob entity ID is) (whatever character you want to select).
Useful for admin events, loading other character's people wanted to be or any use that requires spawning a character in-game.
**Changelog**
:cl:
- add: Added Loadcharacter command
=> Added Load Character Command

Resources/Prototypes/Roles/Jobs/Cargo/quartermaster.yml, Resources/Prototypes/Roles/Jobs/Cargo/salvage_specialist.yml, Resources/Prototypes/Roles/Jobs/Civilian/bartender.yml, Resources/Prototypes/Roles/Jobs/Civilian/detective.yml, Resources/Prototypes/Roles/Jobs/Civilian/lawyer.yml, Resources/Prototypes/Roles/Jobs/Civilian/mime.yml, Resources/Prototypes/Roles/Jobs/Command/captain.yml, Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml, Resources/Prototypes/Roles/Jobs/Engineering/atmospheric_technician.yml, Resources/Prototypes/Roles/Jobs/Engineering/chief_engineer.yml, Resources/Prototypes/Roles/Jobs/Engineering/station_engineer.yml, Resources/Prototypes/Roles/Jobs/Engineering/technical_assistant.yml, Resources/Prototypes/Roles/Jobs/Medical/chemist.yml, Resources/Prototypes/Roles/Jobs/Medical/chief_medical_officer.yml, Resources/Prototypes/Roles/Jobs/Medical/medical_doctor.yml, Resources/Prototypes/Roles/Jobs/Medical/medical_intern.yml, Resources/Prototypes/Roles/Jobs/Medical/paramedic.yml, Resources/Prototypes/Roles/Jobs/Science/borg.yml, Resources/Prototypes/Roles/Jobs/Science/research_assistant.yml, Resources/Prototypes/Roles/Jobs/Science/research_director.yml, Resources/Prototypes/Roles/Jobs/Science/scientist.yml, Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml, Resources/Prototypes/Roles/Jobs/Security/security_cadet.yml, Resources/Prototypes/Roles/Jobs/Security/security_officer.yml, Resources/Prototypes/Roles/Jobs/Security/warden.yml
Removed time requirements for all jobs. This will be temporary until the server is opened publicly. 
Server's in a play-test phase, so doing this change allows play testers to see and try out new stuff without having to give them playtime to be those roles.
=> Temp Removal of Role Time Requirements

Resources/Prototypes/Roles/Jobs/Cargo/salvage_specialist.yml
Merged upstream [Merge Upstream 4.16.24](https://github.com/greystation14/GreyStation14/pull/163#top)
#163 and forgot to add this quick fix.
Just fixes placement.
=> Quick Fix for Cargo Headset

Resources/Prototypes/GreyStation/Roles/Jobs/Fun/misc_startinggear.yml, Resources/Prototypes/Nyanotrasen/Roles/Jobs/Security/prisonguard.yml, Resources/Prototypes/Nyanotrasen/Roles/Jobs/Wildcards/gladiator.yml, Resources/Prototypes/Nyanotrasen/Roles/Jobs/Wildcards/martialartist.yml, Resources/Prototypes/Nyanotrasen/Roles/Jobs/Wildcards/prisoner.yml, Resources/Prototypes/Roles/Jobs/Cargo/salvage_specialist.yml, Resources/Prototypes/Roles/Jobs/Engineering/atmospheric_technician.yml
Fixes some loadout bugs from previous wizden merge of loadout system.
WHY?? Because having it fixed is good.
=> Loadout Fixes

Resources/Prototypes/Entities/Mobs/Player/human.yml
=> Return of the Urist Cloned Syndicate Agents

Resources/Prototypes/DeltaV/Entities/Mobs/NPCs/nukiemouse.yml, Resources/Prototypes/GreyStation/Entities/Mobs/NPCs/xeno.yml
Fixed and updated Nukie Mouse + Vasquez
**Changelog**
:cl:
- fix: Fixed nuclear mouse operatives and Vasquez the Xeno Maid
=> Update + Fix Nukie Mouse and Vasquez

Resources/Prototypes/Entities/Objects/Misc/books.yml, Resources/Prototypes/GreyStation/Entities/Objects/Misc/books.yml
Swapped it out for GreyStations version of Space Law book.
They call me Johnny tight lips and I ain't sharin' nothin'
=> Remove WizDen Space Law Book for GreyStation Space Law Book

Resources/Prototypes/Entities/Clothing/Masks/masks.yml
COMPLIANCE IS IN YOUR BEST INTEREST - HoS's hailer
=> Swat Mask Parents Sec Mask + Explorer Mask stats

Resources/Prototypes/Catalog/Cargo/cargo_vending.yml, Resources/Prototypes/GreyStation/Entities/Clothing/Eyes/glasses.yml
New tequila shades makes the restock to be updated
=> Update Restock Cost for Theater-Drobe

Resources/Prototypes/Entities/Markers/Spawners/Random/maintenance.yml, Resources/Prototypes/GreyStation/Entities/Objects/Misc/quarter.yml, Resources/Prototypes/Loadouts/Miscellaneous/trinkets.yml, Resources/Prototypes/Loadouts/loadout_groups.yml
=> Quarter Tweaks - Added to loadout trinkets + maintenance loot pile

Content.Shared/GreyStation/Flipping/FlippableCoinSystem.cs
it gets removed from bags/lockers/etc too so you cant do very easy sound spam
right now it spins which looks a bit weird at times, but not having spin looks really bad if direction doesnt change much since it always faces the same way
https://github.com/user-attachments/assets/5ac42258-8ae7-4510-a8e1-8e587877a805
=> flipping a coin throws it slightly

Content.Shared/GreyStation/Flipping/FlippableCoinSystem.cs
=> fix z flipping

Resources/Locale/en-US/nyanotrasen/job/job-names.ftl, Resources/Prototypes/DeltaV/Entities/Clothing/Hands/gloves.yml, Resources/Prototypes/DeltaV/StatusEffects/job.yml, Resources/Prototypes/GreyStation/Entities/Clothing/Hands/colored.yml, Resources/Prototypes/Nyanotrasen/Entities/Structures/Lighting/base_lighting.yml, Resources/Prototypes/Nyanotrasen/StatusIcon/job.yml
I fixed some issues with DeltaV and Nyanotrasen job YML and updated them. Also fixed some gloves that have a removed HeatResistance prototype.
We wanna play spess men game, need it to work to play.
=> Upstream Merge Fixes 8.9.24

Resources/Prototypes/Nyanotrasen/Entities/Objects/Consumable/Food/candy.yml, Resources/Prototypes/Nyanotrasen/Entities/Objects/Consumable/Food/meals.yml, Resources/Prototypes/Nyanotrasen/Entities/Objects/Consumable/Food/snacks.yml
=> Fix Nyano/DeltaV Food YML

Resources/Prototypes/Maps/Pools/default.yml
Removed some maps from the map pool.
I think too many maps that cause bloating can relay into bad gameplay. A handful of maps is more then plenty and will make it easier to manage and modify maps for our custom content in the future.
**Changelog**
:cl:
- remove: Removed maps from the map pool
=> Map Pool Changes

Resources/Prototypes/SoundCollections/screams.yml
Updated plant screams sound collection.
I think the male screams are funnier.
=> Update Plant Scream YML

Content.Shared/GreyStation/Weapons/Leech/LeechOnHitComponent.cs, Content.Shared/GreyStation/Weapons/Leech/LeechOnHitSystem.cs
adds `LeechOnHit` which will heal you when you attack a living mob.
- the mob cant be you...
- if you wide swing 3 urists you only get healed once instead of triple
- if you hit crit or dead mobs it wont heal you since gibbing someone as a medkit is bad
important to note the values are negative, if theyre positive itll hurt you instead
```yml
- type: LeechOnHit
leech:
groups:
Brute: -15 # heal up to 5 damage of blunt/slash/piercing
types:
Blunt: -10 # heal 10 blunt 
```
=> add LeechOnHit component/system

Resources/Maps/Shuttles/ShuttleEvent/commieshuttle.yml
Added the ship for a future syndicate team antagonist.
It's a rust bucket glass cannon with giant lasers on the front and side of it, nuff' said.
Until there's ways for the crew to directly deal with attacking ship targets, this won't be fully implemented.
=> Commie Shuttle Added

Resources/Prototypes/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml, Resources/Prototypes/GreyStation/Actions/hailer.yml, Resources/Prototypes/GreyStation/Catalog/Fills/Backpacks/StarterGear/dufflebag.yml, Resources/Prototypes/GreyStation/Entities/Objects/Weapons/Guns/Projectiles/impacts.yml, Resources/Prototypes/GreyStation/Objectives/traitor.yml, Resources/Prototypes/Nyanotrasen/Entities/Objects/Consumable/Food/ration.yml
New upstream changes make it so nospawn doesn't work and you have to use categories: [ HideSpawnMenu ] to have the same effect.
To make the YML work
=> Replace nospawn with  categories: [ HideSpawnMenu ]

.github/workflows/labeler-untriaged.yml, Content.Server/Ame/Components/AmeControllerComponent.cs, Content.Shared/CCVar/CCVars.Game.cs, Content.Shared/CCVar/CCVars.Ic.cs
=> tweak ccvar + AME sound fix

Resources/Prototypes/Datasets/ion_storm.yml
Added more inclusive phrases for ion storm laws
For more funny scenarios and be more similar to SS13's Ion Storm Laws
**Changelog**
:cl:
- add: Added more inclusive Ion Storm laws
=> Make Ion Storm Laws more inclusive

Resources/Prototypes/Entities/Markers/Spawners/Random/vending.yml, Resources/Prototypes/Entities/Markers/Spawners/Random/vendingdrinks.yml, Resources/Prototypes/Entities/Structures/Machines/vending_machines.yml
Removed bloat vendings
Cut bloat
**Changelog**
:cl:
- remove: Removed Pride-O-Mat Vending Machine
- remove: Removed Smite Vending Machine
=> Remove Bloat Vendings

Content.Server/GreyStation/Hailer/DeathgaspMaskSystem.cs, Content.Shared/GreyStation/Hailer/DeathgaspMaskComponent.cs, Content.Shared/GreyStation/Hailer/SharedHailerSystem.cs
=> fix build realer
